version: '3.6'
services:
  app:
    container_name: app_ws
    build: .
    stdin_open: ${DOCKERTTY}
    tty: ${DOCKERTTY}
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/root/.ssh
      - ./public/system:/usr/src/app/public/system
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - sidekiq

  db:
    image: postgres:9.6.4
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server

  sidekiq:
    build: .
    command: bundle exec sidekiq -v -q default -q mailers
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
