oauth_2_0:
   type: OAuth 2.0
   description: The API supports OAuth 2.0 for authenticating all API requests.
   settings:
      authorizationUri: https://api.template.com/oauth/authorize
      accessTokenUri: https://api.template.com/oauth/token
      authorizationGrants: [ password ]
